// These constants represent the RISC-V ELF and the image ID generated by risc0-build.
// The ELF is used for proving and the ID is used for verification.
use methods::{RISC0_GRANDINE_STATE_TRANSITION_ELF, RISC0_GRANDINE_STATE_TRANSITION_ID};
use risc0_zkvm::{default_prover, ExecutorEnv};

use std::time::Instant;

use anyhow::Result;
use ssz::{SszHash as _, SszRead as _};
use types::{combined::BeaconState, config::Config, preset::Mainnet, traits::BeaconState as _};

fn main() -> Result<()> {
    tracing_subscriber::fmt()
        .with_env_filter(tracing_subscriber::filter::EnvFilter::from_default_env())
        .init();

    let config = Config::pectra_devnet_4();

    let block_ssz = std::fs::read(
        "./data/pectra-devnet-4/block_224320_0xb6be0a7bc632809e85c9176db3f195418c29c1cfeab559be094de61339ba97ee.ssz",
    )?;

    let state_ssz = std::fs::read(
        "./data/pectra-devnet-4/state_224319_0x7ece9f54e1112ba2b006ce90903015527e8bd4ca3c3abfff991c281b7dd19c4c.ssz",
    )?;

    let started_at = Instant::now();

    let env = ExecutorEnv::builder()
        .write(&block_ssz.len())?
        .write(&state_ssz.len())?
        .write_slice(&block_ssz)
        .write_slice(&state_ssz)
        .build()?;

    let prover = default_prover();

    let prove_info = prover.prove(env, RISC0_GRANDINE_STATE_TRANSITION_ELF)?;

    let receipt = prove_info.receipt;

    let output_bytes = &receipt.journal.bytes;
    let state = BeaconState::<Mainnet>::from_ssz(&config, output_bytes)?;

    println!("elapsed: {} ms", started_at.elapsed().as_millis());

    // Expected: 0x7e0b9074b594303bd466cdc11c54ee3eb8bb3b424bc1301995d47b12062bc807
    // See: https://dora.pectra-devnet-4.ethpandaops.io/slot/224320
    let state_root = state.hash_tree_root();

    println!("state slot after state transition: {}", state.slot());
    println!("state root after state transition: {state_root:?}");

    receipt.verify(RISC0_GRANDINE_STATE_TRANSITION_ID)?;

    Ok(())
}
