[package]
name = "risc0_grandine_state_transition"
version = "0.1.0"
edition = "2021"

[workspace]

[dependencies]
anyhow = '1.0.93'
risc0-zkvm = { version = "2.0.2", default-features = false, features = ['std'] }
ssz = { path = '../../../ssz' }
transition_functions = { path = '../../../transition_functions', features = ['zkcrypto'] }
types = { path = '../../../types', features = ["zkcrypto"] }
